service: IWIBotBackend
provider:
  name: openwhisk
package:
  name: IWIBot
  testname: IWIBotTest
  testbasepath: /iwibotTest
  individually: true
  exclude:
    - '**/*'
triggers: null
plugins:
  - iwibot-serverless-build-plugin
functions:
  Schwimmbad:
    enabled: false
    name: Schwimmbad
    runtime: java
    handler: de.hska.iwibot.actions.java.Schwimmbad
    relpath: java-schwimmbad
    package:
      name: IWIBot
      include:
        - src/**/*
        - pom.xml
        - README.md
  Joke:
    enabled: false
    name: Joke
    runtime: 'nodejs:8'
    handler: lib/Joke.main
    relpath: nodejs-joke
    package:
      name: IWIbot_dev
      include:
        - lib/**/*
        - package.json
        - README.md
  Bescheinigung:
    enabled: false
    name: Bescheinigung
    runtime: 'nodejs:8'
    handler: lib/Bescheinigung.main
    relpath: nodejs-bescheinigung
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  Meal:
    enabled: false
    name: Meal
    runtime: 'nodejs:8'
    handler: lib/Meal.main
    relpath: nodejs-meal
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  Router:
    enabled: true
    name: Router
    runtime: 'nodejs:8'
    handler: lib/Router.main
    relpath: nodejs-router
    parameters:
      workspace_id: 4b9aa897-7134-4dbb-9b87-2b4ef6e47fac
    annotations:
      web-export: true
    bind:
      - service:
          type: conversation
          key: Serviceberechtigungsnachweise-1
          instance: conversation-1
    events:
      - http:
          basepath: /iwibot
          relpath: /router
          operation: post
          responsetype: http
          cors: true
    package:
      name: IWIbot_dev
      include:
        - lib/**/*
        - package.json
        - README.md
  Semester:
    enabled: false
    name: Semester
    runtime: 'nodejs:8'
    handler: lib/Semester.main
    relpath: nodejs-semester
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  Sprechstunde:
    enabled: false
    name: Sprechstunde
    runtime: 'nodejs:8'
    handler: lib/Sprechstunde.main
    relpath: nodejs-sprechstunde
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  Timetable:
    enabled: false
    name: Timetable
    runtime: 'nodejs:8'
    handler: lib/Timetable.main
    relpath: nodejs-timetable
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  Weather:
    enabled: false
    name: Weather
    runtime: 'nodejs:8'
    handler: lib/Weather.main
    relpath: nodejs-weather
    bind:
      - service:
          type: weatherinsights
          key: Serviceberechtigungsnachweise-1
          instance: weatherinsights
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  Wikipedia:
    enabled: false
    name: Wikipedia
    runtime: 'nodejs:8'
    handler: lib/Wikipedia.main
    relpath: nodejs-wikipedia
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  Modulhandbuch:
    enabled: false
    name: Modulhandbuch
    runtime: 'nodejs:8'
    handler: lib/Modulhandbuch.main
    relpath: nodejs-modulhandbuch
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  Template-PHP:
    enabled: false
    name: Template-PHP
    runtime: 'php:7.2'
    handler: lib/index.main
    relpath: template-php
    package:
      name: IWIBot
      include:
        - lib/**/*
        - vendor/**/*
        - composer.json
        - README.md
  Template-Go:
    enabled: false
    name: Template-Go
    runtime: blackbox
    kind: go
    handler: bin/exec
    relpath: template-go
    package:
      name: IWIBot
      include:
        - bin/exec
  Template-Python:
    enabled: false
    name: Template-Python
    runtime: 'python:3'
    handler: lib/__main__.main
    module: template-python
    relpath: template-python
    package:
      name: IWIBot
      include:
        - lib/**/*
        - requirements.txt
        - README.md
  Template-Java:
    enabled: false
    name: Template-Java
    runtime: java
    handler: de.hska.iwibot.actions.java.Template
    relpath: template-java
    package:
      name: IWIBot
      include:
        - src/**/*
        - pom.xml
        - README.md
  Template-Nodejs:
    enabled: false
    name: Template-Nodejs
    runtime: 'nodejs:8'
    handler: lib/Test.main
    relpath: template-nodejs
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  test:
    enabled: false
    relpath: nodejs-test
    name: test
    runtime: 'nodejs:8'
    handler: lib/test.main
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
