service: IWIBotBackend
provider:
  name: openwhisk
package:
  name: IWIBot
  testname: IWIBotTest
  testbasepath: /iwibotTest
  individually: true
  exclude:
    - '**/*'
triggers: null
plugins:
  - iwibot-serverless-build-plugin
functions:
  # Infrastructure: central routing function
  Router:
    enabled: true
    name: Router
    runtime: 'nodejs:8'
    handler: lib/Router.main
    relpath: nodejs-router
    parameters:
      workspace_id: af980ed8-85a6-41d0-9d6a-69186c582d0b
    annotations:
      web-export: true
    bind:
      - service:
          type: conversation
          key: Serviceberechtigungsnachweise-1
          instance: TBA!!!
    events:
      - http:
          basepath: /iwibot
          relpath: /router
          operation: post
          responsetype: http
          cors: true
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Infrastructure: generic session service
  Sessions:
    enabled: true
    relpath: nodejs-sessions
    name: Sessions
    runtime: 'nodejs:8'
    handler: lib/Sessions.main
    bind:
      - service:
        type: cloudantnosqldb
        key: Serviceberechtigungsnachweise-1
        instance: Cloudant-xt
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Infrastructure: generic crypto key service
  Keys:
    enabled: true
    relpath: nodejs-keys
    name: Keys
    runtime: 'nodejs:8'
    handler: lib/Keys.main
    annotations:
      web-export: true
    events:
      - http:
          basepath: /iwibot
          relpath: /keys
          operation: post
          responsetype: http
          cors: true
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Capabilities: Schwimmbad Zeiten
  Schwimmbad:
    enabled: false
    name: Schwimmbad
    runtime: java
    handler: de.hska.iwibot.actions.java.Schwimmbad
    relpath: java-schwimmbad
    package:
      name: IWIBot
      include:
        - src/**/*
        - pom.xml
        - README.md
  # Capabilities: Joke
  Joke:
    enabled: true
    name: Joke
    runtime: 'nodejs:8'
    handler: lib/Joke.main
    relpath: nodejs-joke
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Capabilities: Bescheinigung ausstellen
  Bescheinigung:
    enabled: false
    name: Bescheinigung
    runtime: 'nodejs:8'
    handler: lib/Bescheinigung.main
    relpath: nodejs-bescheinigung
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Capabilities: Mensa Abfrage
  Meal: 
    enabled: false
    name: Meal
    runtime: 'nodejs:8'
    handler: lib/Meal.main
    relpath: nodejs-meal
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Capabilities: Semester 
  Semester:
    enabled: false
    name: Semester
    runtime: 'nodejs:8'
    handler: lib/Semester.main
    relpath: nodejs-semester
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Capabilities: Sprechstunden
  Sprechstunde:
    enabled: false
    name: Sprechstunde
    runtime: 'nodejs:8'
    handler: lib/Sprechstunde.main
    relpath: nodejs-sprechstunde
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Capabilities: Stundenplan Abfrage
  Timetable:
    enabled: false
    name: Timetable
    runtime: 'nodejs:8'
    handler: lib/Timetable.main
    relpath: nodejs-timetable
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Capabilities: Wetterbericht
  Weather:
    enabled: false
    name: Weather
    runtime: 'nodejs:8'
    handler: lib/Weather.main
    relpath: nodejs-weather
    bind:
      - service:
          type: weatherinsights
          key: Serviceberechtigungsnachweise-1
          instance: Weather-g1
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Capabilities: Wikipedia Abfrage
  Wikipedia:
    enabled: false
    name: Wikipedia
    runtime: 'nodejs:8'
    handler: lib/Wikipedia.main
    relpath: nodejs-wikipedia
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Capabilities: Modulhandbuch Abfrage
  Modulhandbuch:
    enabled: false
    name: Modulhandbuch
    runtime: 'nodejs:8'
    handler: lib/Modulhandbuch.main
    relpath: nodejs-modulhandbuch
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Templates: PHP Basis
  Template-PHP:
    enabled: false
    name: Template-PHP
    runtime: 'php:7.2'
    handler: lib/index.main
    relpath: template-php
    package:
      name: IWIBot
      include:
        - lib/**/*
        - vendor/**/*
        - composer.json
        - README.md
  # Templates: Go Basis
  Template-Go:
    enabled: false
    name: Template-Go
    runtime: blackbox
    kind: go
    handler: bin/exec
    relpath: template-go
    package:
      name: IWIBot
      include:
        - bin/exec
  # Templates: Python Basis
  Template-Python:
    enabled: false
    name: Template-Python
    runtime: 'python:3'
    handler: lib/__main__.main
    module: template-python
    relpath: template-python
    package:
      name: IWIBot
      include:
        - lib/**/*
        - requirements.txt
        - README.md
  # Templates: Java Basis
  Template-Java:
    enabled: false
    name: Template-Java
    runtime: java
    handler: de.hska.iwibot.actions.java.Template
    relpath: template-java
    package:
      name: IWIBot
      include:
        - src/**/*
        - pom.xml
        - README.md
  # Templates: Javascript Basis
  Template-Nodejs:
    enabled: false
    name: Template-Nodejs
    runtime: 'nodejs:8'
    handler: lib/Test.main
    relpath: template-nodejs
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
  # Misc:
  test:
    enabled: false
    relpath: nodejs-test
    name: test
    runtime: 'nodejs:8'
    handler: lib/test.main
    package:
      name: IWIBot
      include:
        - lib/**/*
        - package.json
        - README.md
